# SPDX-FileCopyrightText: 2023 Christina Sørensen
# SPDX-FileContributor: Christina Sørensen
#
# SPDX-License-Identifier: AGPL-3.0-only

## Rime Application Kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Making sure all resources used are created in a dedicated namespace
# Also specific annotations are added for later identification
namespace: rime
commonAnnotations:
  provider: kubernetes-cafkafk-rime

# rime resources (namespace, services, deployments, etc)
resources:
  - resources/namespace.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/load-balancer-service.yaml
